version: 2
jobs:
  build:
    # the image factory
    docker:
      - image: debian:stretch-slim
    steps:
      - run: apt-get -y update
      - run: apt-get -y install coreutils qemu gawk sed curl wget make git ssh gnupg2
      - run: echo 'deb http://download.virtualbox.org/virtualbox/debian stretch contrib' > /etc/apt/sources.list.d/virtualbox.list
      - run: wget https://www.virtualbox.org/download/oracle_vbox_2016.asc -O /tmp/oracle_vbox_2016.asc
      - run: apt-key add /tmp/oracle_vbox_2016.asc
      - run: apt-get -y update
      - run: apt-get -y install virtualbox-6.0
      - checkout
      - run: make debian-stretch
      - run: make ubuntu-bionic
      - run: make centos
  publish:
    # publishes the artificats to github
    docker:
      - image: debian:stretch-slim
    steps:
      - run: apt-get -y update
      - run: apt-get -y install unzip wget git ssh gnupg2
      - checkout
      - run: make install-ghr
      - run: make todist
      - run: make publish
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish
